# ruff: noqa: E501
"""Add the second half of the Python knowledge-practice pairs.

The first generator covers syntax and built-in containers. This companion
catalog keeps the same Chinese beginner contract for functions, files,
exceptions, modules, object orientation, data processing and algorithms.
"""

from __future__ import annotations

from expand_python_beginner_practice import (
    EXERCISES,
    Task,
    _enrich_concept,
    _exercise,
    _write,
)

TASKS = (
    Task(
        "PY-CONTAINER-01", "课后练习：读取成绩矩阵的一列",
        "第一行读取行数 n 和列数 m，随后读取 n 行整数矩阵，最后读取列索引 k。按原行顺序输出第 k 列，元素以空格分隔。",
        "n, m = map(int, input().split())\nmatrix = []\n# 读取每一行并保存，再读取 k\n",
        (("public-column", "3 3\n1 2 3\n4 5 6\n7 8 9\n1\n", "2 5 8\n"),),
        (("hidden-first", "2 2\n5 6\n7 8\n0\n", "5 7\n"),),
        "第一行 n m；随后 n 行、每行 m 个整数；最后一行列索引 k。", "目标列的 n 个整数，以空格分隔。",
        ("1 <= n,m <= 50", "0 <= k < m"),
        ("外层列表保存每一行", "matrix[row][k] 访问第 row 行第 k 列", "先用 2×2 矩阵检查下标"),
        "concept: nested lists / indexing", "读取两行数字并输出第二行第一个元素。",
        "matrix = [[1, 2], [3, 4]]\nprint(matrix[1][0])\n",
        "matrix[1][0] 中两个索引分别表示什么？", "遇到嵌套容器时，先画出外层元素，再逐层写索引。", estimated_minutes=20,
    ),
    Task(
        "PY-DATA-01", "课后练习：清洗缺失的温度记录",
        "读取一行逗号分隔的数据，其中 NA 表示缺失。忽略 NA，输出有效数据个数和平均值；平均值保留 1 位小数。",
        "fields = input().split(',')\n# 过滤 NA，再转换为数值\n",
        (("public-missing", "12,NA,18,15\n", "3 15.0\n"),),
        (("hidden-none", "2,4,6\n", "3 4.0\n"), ("hidden-one", "NA,7,NA\n", "1 7.0\n")),
        "一行逗号分隔的整数或 NA。", "有效数据个数 平均值。",
        ("至少包含一个有效整数", "平均值固定保留 1 位小数"),
        ("先按逗号拆分", "先过滤 NA，再调用 int()", "用全有效和仅一个有效值分别测试"),
        "curriculum: data cleaning / missing values", "从文本列表中去掉空字符串。",
        "values = ['12', '', '18']\nclean = [item for item in values if item]\nprint(clean)\n",
        "为什么应该先判断 NA，再做整数转换？", "数据清洗要记录哪些值被丢弃，真实项目中不能悄悄忽略异常。", estimated_minutes=20,
    ),
    Task(
        "PY-DATA-02", "课后综合：汇总分类交易额",
        "第一行读取记录数 n，随后 n 行包含类别和整数金额。汇总每个类别的金额，按类别字典序逐行输出“类别 总额”。",
        "n = int(input())\ntotals = {}\n# 读取记录并完成分组汇总\n",
        (("public-sales", "4\nA 10\nB 7\nA 5\nC 2\n", "A 15\nB 7\nC 2\n"),),
        (("hidden-negative", "3\nx 5\nx -2\ny 0\n", "x 3\ny 0\n"),),
        "第一行 n；随后 n 行：类别 金额。", "按类别字典序输出各类别总额。",
        ("1 <= n <= 1000", "金额为整数", "类别不含空格"),
        ("用字典保存类别到累计值的映射", "get(category, 0) 处理首次出现", "输出前对字典键排序"),
        "curriculum: data aggregation / grouping", "把同类商品的数量累加到字典。",
        "totals = {}\nfor name, value in [('A', 2), ('A', 3)]:\n    totals[name] = totals.get(name, 0) + value\nprint(totals)\n",
        "为什么分组汇总通常需要“键”和“累计值”两个角色？", "综合数据题按读取、清洗、汇总、排序、输出五步实现。",
        difficulty="advanced", estimated_minutes=25,
    ),
    Task(
        "PY-EXC-01", "课后 Debug：安全完成除法",
        "读取两个文本。能转换为数字且除数不为零时输出商（保留 2 位小数）；输入非法输出“输入错误”，除数为零输出“不能除以零”。请用异常处理修复程序。",
        "a_text, b_text = input().split()\na = float(a_text)\nb = float(b_text)\nprint(f'{a / b:.2f}')\n",
        (("public-ok", "8 2\n", "4.00\n"), ("public-zero", "8 0\n", "不能除以零\n")),
        (("hidden-invalid", "abc 2\n", "输入错误\n"),),
        "一行两个文本。", "商、输入错误或不能除以零。",
        ("分别处理 ValueError 与 ZeroDivisionError", "不得输出异常堆栈"),
        ("把转换和除法放入 try", "为两类异常编写不同 except", "正常结果放在 try 的成功路径"),
        "concept: exceptions / error handling", "捕获整数转换失败。",
        "try:\n    number = int('abc')\nexcept ValueError:\n    print('无法转换')\n",
        "为什么不建议用一个不写异常类型的 except 捕获所有错误？", "异常处理应捕获可预期错误，并给用户明确、有限的信息。",
        exercise_type="debug", estimated_minutes=20,
    ),
    Task(
        "PY-EXC-02", "课后练习：定义成绩范围异常",
        "定义 ScoreRangeError。读取一个整数分数；若不在 0 到 100，抛出并捕获该异常，输出“分数越界”；否则输出“有效分数:分数”。",
        "class ScoreRangeError(ValueError):\n    pass\n\nscore = int(input())\n# 校验、抛出并捕获自定义异常\n",
        (("public-valid", "80\n", "有效分数:80\n"), ("public-low", "-1\n", "分数越界\n")),
        (("hidden-high", "101\n", "分数越界\n"), ("hidden-edge", "100\n", "有效分数:100\n")),
        "一个整数分数。", "有效分数:分数，或分数越界。",
        ("合法范围包含 0 和 100", "自定义异常继承 ValueError"),
        ("先定义异常类", "条件不满足时 raise ScoreRangeError", "只捕获自己预期的异常类型"),
        "concept: custom exceptions", "用 ValueError 表示参数值不符合约束。",
        "def require_positive(value):\n    if value <= 0:\n        raise ValueError('必须为正数')\n",
        "什么情况下自定义异常比直接返回 False 更清晰？", "自定义异常用于表达稳定的业务或领域错误，不要为每一行代码新建异常类。",
        difficulty="advanced", estimated_minutes=25,
    ),
    Task(
        "PY-FILE-01", "课后练习：在内存文件中写学习日志",
        "读取一行学习内容，使用 io.StringIO 模拟文本文件：写入“今日学习:内容”后读取并原样输出。",
        "from io import StringIO\ncontent = input().strip()\n# 创建内存文本文件，写入后把指针移回开头再读取\n",
        (("public-text", "列表\n", "今日学习:列表\n"),), (("hidden-text", "异常处理\n", "今日学习:异常处理\n"),),
        "一行非空学习内容。", "一行学习日志。",
        ("使用 StringIO 模拟文件，避免依赖本机路径", "读取前需要 seek(0)"),
        ("StringIO() 创建内存文本流", "write() 后指针位于末尾", "seek(0) 后再 read()"),
        "concept: file read-write / safe in-memory practice", "向内存文件写入 hello 并读回。",
        "from io import StringIO\nfile = StringIO()\nfile.write('hello')\nfile.seek(0)\nprint(file.read())\n",
        "写入后为什么直接 read() 可能得到空字符串？", "初学阶段先理解文件指针；真实路径和权限问题留到项目环境练习。", estimated_minutes=20,
    ),
    Task(
        "PY-FILE-02", "课后 Debug：用 with 管理文本流",
        "读取一行文本，使用 with 和 io.StringIO 读取内容并输出大写形式。修复当前未正确使用上下文管理器的代码。",
        "from io import StringIO\ntext = input()\nfile = StringIO(text)\ncontent = file.read()\nprint(content.upper())\n",
        (("public-word", "Python\n", "PYTHON\n"),), (("hidden-phrase", "hello world\n", "HELLO WORLD\n"),),
        "一行文本。", "该文本的大写形式。", ("必须使用 with StringIO(text) as file", "不要在 with 结束后再次读取已关闭对象"),
        ("把资源创建写在 with 后", "缩进读取操作", "离开 with 后只使用已读取的普通字符串"),
        "concept: context manager / with", "使用 with 自动关闭内存文本流。",
        "from io import StringIO\nwith StringIO('hello') as file:\n    content = file.read()\nprint(content)\n",
        "with 代码块结束时，资源会发生什么？", "with 把获取和释放资源写在同一结构里，减少忘记关闭的问题。",
        exercise_type="debug", estimated_minutes=20,
    ),
    Task(
        "PY-FILE-03", "课后练习：读取 CSV 成绩",
        "第一行读取记录数 n，随后 n 行为“姓名,成绩”。使用 csv.reader 读取，输出平均成绩，保留 1 位小数。",
        "import csv\nimport sys\n\nn = int(input())\n# 使用 csv.reader 读取接下来的 n 行\n",
        (("public-three", "3\n小词,80\n小元,90\n小码,70\n", "80.0\n"),), (("hidden-one", "1\nA,100\n", "100.0\n"),),
        "第一行 n；随后 n 行 CSV，每行姓名,整数成绩。", "平均成绩，保留 1 位小数。",
        ("1 <= n <= 100", "0 <= 成绩 <= 100"),
        ("csv.reader(sys.stdin) 可以继续读取标准输入", "每行解包为 name 和 score_text", "只累计前 n 条记录"),
        "concept: CSV / standard library", "用 csv.reader 解析一行带逗号的数据。",
        "import csv\nfrom io import StringIO\nrow = next(csv.reader(StringIO('A,90')))\nprint(row)\n",
        "为什么 CSV 中含引号和逗号时不宜简单使用 split(',')？", "结构化文件应优先使用标准解析器，而不是手写脆弱的分隔规则。", estimated_minutes=25,
    ),
    Task(
        "PY-FILE-04", "课后练习：规范化 JSON",
        "读取一行 JSON 对象，使用 json.loads 解析，再使用 json.dumps 按键排序、紧凑输出；中文不得转义为 Unicode 编码。",
        "import json\ntext = input()\n# 解析后按键排序，并关闭中文转义\n",
        (("public-order", "{\"name\":\"小词\",\"age\":18}\n", "{\"age\":18,\"name\":\"小词\"}\n"),),
        (("hidden-bool", "{\"ok\":true,\"count\":2}\n", "{\"count\":2,\"ok\":true}\n"),),
        "一行合法 JSON 对象。", "键已排序的紧凑 JSON。",
        ("使用 ensure_ascii=False", "使用 sort_keys=True", "分隔符中不保留额外空格"),
        ("json.loads 把文本转为 Python 对象", "json.dumps 完成反向序列化", "设置 separators=(',', ':') 生成紧凑格式"),
        "concept: JSON serialization", "把字典序列化为 JSON 文本。",
        "import json\ndata = {'name': '小词'}\nprint(json.dumps(data, ensure_ascii=False))\n",
        "JSON 的 true 与 Python 的 True 在解析前后分别属于哪种表示？", "JSON 是交换格式；不要用 eval 解析外部 JSON 文本。", estimated_minutes=25,
    ),
    Task(
        "PY-FUNC-01", "课后练习：封装问候函数",
        "定义 greet(name) 并返回“你好，name！”。读取姓名，调用函数并输出返回值；姓名需去除首尾空格。",
        "def greet(name):\n    # 返回问候语，不在函数内直接打印\n    pass\n\nname = input()\nprint(greet(name))\n",
        (("public-name", "小词\n", "你好，小词！\n"),), (("hidden-spaces", "  小元  \n", "你好，小元！\n"),),
        "一行姓名。", "一行问候语。", ("函数必须有返回值", "姓名去除首尾空格"),
        ("def 后写清参数 name", "函数体中先清理 name", "用 return 返回字符串"),
        "concept: functions / definition and call", "定义一个返回两倍值的函数。",
        "def double(number):\n    return number * 2\n\nprint(double(3))\n",
        "return 与 print 的职责有什么不同？", "函数优先返回结果，由调用者决定如何展示或继续计算。", estimated_minutes=15,
    ),
    Task(
        "PY-FUNC-02", "课后练习：计算加权成绩",
        "定义 weighted_score(homework, exam, homework_weight=0.4)，返回加权成绩。读取作业分和考试分，输出结果并保留 1 位小数。",
        "def weighted_score(homework, exam, homework_weight=0.4):\n    # 考试权重为 1 - homework_weight\n    pass\n\nhomework, exam = map(float, input().split())\nprint(f'{weighted_score(homework, exam):.1f}')\n",
        (("public-normal", "80 90\n", "86.0\n"),), (("hidden-same", "70 70\n", "70.0\n"),),
        "一行两个数字：作业分 考试分。", "默认权重下的加权成绩，保留 1 位小数。",
        ("0 <= 分数 <= 100", "默认作业权重为 0.4"),
        ("默认参数写在形参列表中", "考试权重是 1 减作业权重", "函数返回数值，格式化在调用处完成"),
        "concept: parameters / return values / defaults", "定义带默认折扣的价格函数。",
        "def price(amount, discount=0.1):\n    return amount * (1 - discount)\n",
        "为什么默认参数通常放在非默认参数之后？", "参数设计要让默认行为清晰，同时允许调用者显式覆盖。", estimated_minutes=20,
    ),
    Task(
        "PY-FUNC-03", "课后练习：用可变参数求平均值",
        "定义 average(*values) 返回所有参数的平均值。读取一行一个或多个整数，解包后调用函数，输出 1 位小数。",
        "def average(*values):\n    # values 是一个元组\n    pass\n\nnumbers = list(map(int, input().split()))\nprint(f'{average(*numbers):.1f}')\n",
        (("public-three", "2 4 6\n", "4.0\n"),), (("hidden-one", "7\n", "7.0\n"),),
        "一行一个或多个整数。", "平均值，保留 1 位小数。", ("至少输入一个数", "调用时使用 *numbers 解包"),
        ("*values 在函数内是元组", "使用 sum 和 len", "调用处的 * 将列表拆成位置参数"),
        "concept: variadic arguments / unpacking", "用 *args 接收任意数量的位置参数。",
        "def count_args(*args):\n    return len(args)\n\nprint(count_args(1, 2, 3))\n",
        "函数定义中的 *values 与调用中的 *numbers 分别做什么？", "可变参数适合数量不固定但角色相同的值，不应掩盖本应明确命名的参数。", estimated_minutes=20,
    ),
    Task(
        "PY-FUNC-04", "课后 Debug：避免误改全局计数",
        "程序希望函数 add_one(value) 返回 value+1，且不依赖或修改全局变量。请修复函数，使输入 5 时输出 6。",
        "count = 100\n\ndef add_one(value):\n    global count\n    count += 1\n    return count\n\nvalue = int(input())\nprint(add_one(value))\n",
        (("public-five", "5\n", "6\n"),), (("hidden-zero", "0\n", "1\n"), ("hidden-negative", "-2\n", "-1\n")),
        "一个整数。", "输入整数加 1。", ("函数不得读取或修改全局 count", "只依据参数 value 计算"),
        ("删除不必要的 global", "返回 value + 1", "用不同输入确认结果不受 count 影响"),
        "concept: scope / pure function", "比较局部变量与全局变量。",
        "value = 10\ndef show():\n    value = 2\n    return value\nprint(show(), value)\n",
        "同名局部变量会自动修改函数外的变量吗？", "能通过参数传入、返回值传出的数据，不要优先使用 global。",
        exercise_type="debug", estimated_minutes=20,
    ),
    Task(
        "PY-FUNC-05", "课后练习：按长度和字典序排序",
        "读取一行单词，使用 sorted 和 lambda：先按长度升序，同长度按单词字典序升序，最后以空格输出。",
        "words = input().split()\n# key 返回一个包含两个排序依据的元组\n",
        (("public-words", "pear a fig apple\n", "a fig pear apple\n"),), (("hidden-tie", "bb aa c\n", "c aa bb\n"),),
        "一行一个或多个单词。", "按规则排序的单词，以空格分隔。", ("保留重复单词", "使用 key=lambda word: (...)"),
        ("第一排序键是 len(word)", "第二排序键是 word", "让 lambda 返回二元组"),
        "concept: lambda / higher-order functions / sorting", "按绝对值排序数字。",
        "numbers = [-3, 1, -2]\nprint(sorted(numbers, key=lambda value: abs(value)))\n",
        "当 key 返回元组时，Python 依次如何比较其中字段？", "lambda 适合短小的一次性规则；复杂逻辑应改用具名函数。", estimated_minutes=20,
    ),
    Task(
        "PY-ITER-01", "课后练习：生成偶数平方",
        "定义生成器 even_squares(n)，依次产生 1 到 n 中偶数的平方。读取 n，将结果以空格输出。",
        "def even_squares(n):\n    # 使用 yield 逐个产生结果\n    pass\n\nn = int(input())\nprint(*even_squares(n))\n",
        (("public-six", "6\n", "4 16 36\n"),), (("hidden-one", "1\n", "\n"), ("hidden-two", "2\n", "4\n")),
        "一个正整数 n。", "偶数平方序列，以空格分隔；没有结果时输出空行。", ("1 <= n <= 10000", "函数使用 yield"),
        ("遍历 range(2, n + 1, 2)", "每次 yield number * number", "生成器不需要一次构造完整列表"),
        "concept: iterators / generators", "用 yield 产生 0、1、2。",
        "def numbers():\n    for value in range(3):\n        yield value\nprint(*numbers())\n",
        "yield 与 return 在函数执行节奏上有什么不同？", "生成器适合逐项处理数据；初学时先关注“需要一个，产生一个”。", estimated_minutes=25,
    ),
    Task(
        "PY-MOD-01", "课后练习：使用 math 计算向上取整",
        "读取路程和每箱可覆盖路程（均为正数），使用 math.ceil 计算至少需要多少箱并输出。",
        "import math\ndistance, capacity = map(float, input().split())\n# 调用 math.ceil\n",
        (("public-fraction", "10 3\n", "4\n"),), (("hidden-exact", "12 3\n", "4\n"), ("hidden-small", "1 5\n", "1\n")),
        "一行两个正数：总路程 单箱覆盖路程。", "至少需要的整数箱数。", ("两个输入都大于 0", "必须使用 math.ceil"),
        ("先 import math", "计算 distance / capacity", "向上取整保证覆盖全部路程"),
        "concept: modules / import", "导入 math 并计算平方根。", "import math\nprint(math.sqrt(9))\n",
        "import math 与 from math import ceil 在调用写法上有何不同？", "导入方式应清晰表达名称来源，避免使用 import *。", estimated_minutes=15,
    ),
    Task(
        "PY-MOD-02", "课后练习：用 Counter 找最高频单词",
        "读取一行单词，使用 collections.Counter 统计频次。输出频次最高的单词；并列时输出字典序最小者，再输出该频次。",
        "from collections import Counter\nwords = input().split()\n# 统计并按 (-频次, 单词) 选择第一项\n",
        (("public-normal", "a b a c b a\n", "a 3\n"),), (("hidden-tie", "pear apple pear apple\n", "apple 2\n"),),
        "一行一个或多个单词。", "最高频单词 频次。", ("至少包含一个单词", "并列按字典序处理"),
        ("Counter(words) 得到频次映射", "items() 提供单词和频次", "排序键使用 (-count, word)"),
        "concept: standard library / collections.Counter", "统计字符频次。",
        "from collections import Counter\nprint(Counter('aba'))\n",
        "为什么最高频并列时还需要明确第二排序规则？", "标准库能减少重复实现，但仍要读清返回结构和并列规则。", estimated_minutes=20,
    ),
    Task(
        "PY-OOP-01", "课后练习：创建学生对象",
        "定义 Student 类，构造方法接收 name 和整数成绩列表，average() 返回平均分。读取姓名和一行成绩，创建对象并输出“姓名 平均分”，平均分保留 1 位。",
        "class Student:\n    def __init__(self, name, scores):\n        # 保存实例属性\n        pass\n\n    def average(self):\n        pass\n\nname = input().strip()\nscores = list(map(int, input().split()))\nstudent = Student(name, scores)\nprint(f'{student.name} {student.average():.1f}')\n",
        (("public-student", "小词\n80 90 100\n", "小词 90.0\n"),), (("hidden-one", "A\n60\n", "A 60.0\n"),),
        "第一行姓名；第二行一个或多个整数成绩。", "姓名 平均分。", ("成绩列表非空", "实例属性通过 self 保存"),
        ("__init__ 中写 self.name 和 self.scores", "average 中使用 self.scores", "方法调用写 student.average()"),
        "concept: classes / objects / instance methods", "定义一个保存名称的简单类。",
        "class Course:\n    def __init__(self, name):\n        self.name = name\ncourse = Course('Python')\nprint(course.name)\n",
        "为什么实例方法的第一个参数通常写作 self？", "类用于把相关数据和行为组织在一起，不要只为包装一个函数而建类。", estimated_minutes=25,
    ),
    Task(
        "PY-ALGO-01", "课后练习：二分查找位置",
        "第一行读取升序且不重复的整数列表，第二行读取目标值。使用二分查找输出目标下标；不存在输出 -1。",
        "numbers = list(map(int, input().split()))\ntarget = int(input())\nleft, right = 0, len(numbers) - 1\n# 在 left <= right 时缩小搜索区间\n",
        (("public-found", "1 3 5 7 9\n7\n", "3\n"),),
        (("hidden-missing", "2 4 6\n5\n", "-1\n"), ("hidden-first", "2 4 6\n2\n", "0\n")),
        "第一行升序整数；第二行目标整数。", "目标下标或 -1。", ("列表非空且元素互不重复", "不得调用 list.index()"),
        ("中点是 (left + right) // 2", "目标更大时令 left = middle + 1", "循环结束仍未找到时输出 -1"),
        "concept: binary search / boundary tests", "比较中间元素后排除一半区间。",
        "numbers = [1, 3, 5]\nmid = (0 + len(numbers) - 1) // 2\nprint(numbers[mid])\n",
        "为什么更新边界时需要加一或减一？", "二分查找重点是区间含义和边界不变量，不是背代码。", difficulty="intermediate", estimated_minutes=25,
    ),
    Task(
        "PY-ALGO-02", "课后练习：递归计算各位数字之和",
        "定义 recursive_digit_sum(n)，用递归返回非负整数各位数字之和。读取 n 并输出结果。",
        "def recursive_digit_sum(n):\n    # 个位数是递归出口\n    pass\n\nn = int(input())\nprint(recursive_digit_sum(n))\n",
        (("public-normal", "1234\n", "10\n"),), (("hidden-zero", "0\n", "0\n"), ("hidden-large", "90009\n", "18\n")),
        "一个非负整数 n。", "n 的各位数字之和。", ("0 <= n <= 10^12", "必须使用递归函数"),
        ("n < 10 时直接返回 n", "n % 10 得到个位", "剩余部分是 n // 10"),
        "concept: recursion / base case", "递归计算 1 到 n 的和。",
        "def total(n):\n    if n == 0:\n        return 0\n    return n + total(n - 1)\n",
        "如果没有递归出口，程序会发生什么？", "先写递归出口，再确认每次调用都让问题规模变小。", difficulty="advanced", estimated_minutes=25,
    ),
)


def main() -> None:
    EXERCISES.mkdir(parents=True, exist_ok=True)
    for task in TASKS:
        _enrich_concept(task)
        target = EXERCISES / f"{task.exercise_id}.yaml"
        if target.exists():
            raise FileExistsError(f"refusing to overwrite existing exercise: {target}")
        _write(target, _exercise(task))
    print(f"expanded {len(TASKS)} additional Python knowledge-practice pairs")


if __name__ == "__main__":
    main()
